## 1.1 연속형 변수와 이산형 변수 

### 연속형 변수 ( continuous variable )

- 무한하고 가산할 수 없는 값들로 구성
- 연속적인 범위 내에 있다는 것을 의미 
- 사람의 키, 무게, 온도, 거리 등등
- 실수로 표현되며, 두 값 사이에는 항상 또 다른 값이 존재할 수 있음. 
- 회귀 분석에서 연속형 변수는 종종 종속 변수(예측하고자 하는 변수)로 사용 된다. 

### 이산형 변수 ( Discrete variable )

- 셀수 있는 분리된 값들로 구성됨
- 정수로 표현되며, 두 값 사이에 다른 값이 존재하지 않음
- 사람의 자녀 수, 학급의 학생 수, 제품의 결함 수 등
- 회귀 분석에서 이산형 변수는 독립 변수로 사용 될 때가 많음 
- 이산형 변수는 때로는 범주형 변수로 간주 될 수 있음.

## 데이터 스케일링과 정규화 

- 데이터 표준화 ( StandardScaler )
    - 특성의 평균을 0, 분산을 1로 조정하여 모든 특성이 동일한 스케일을 갖도록 변환하는 방법 
    - 우리가 다루는 데이터들의 크기가 너무 다를 때 발생하는 문제를 해결하기 위해 사용 
        - 단위를 없애는 과정이라고 생각하면 됨 

### 장점

- 특성 간 스케일 차이를 감소, 모델이 각 특성을 좀 더 균등하게 취급하도록 도와줌 
- 데이터를 정규 분포에 가깝게 만들어, 많은 머신 러닝 알고리즘의 기본 가정에 부합하게 만듬 
- 표준화된 특성은 최적화 알고리즘의 수렴을 빠르고 효율적으로 만들어, 모델의 학습 과정의 성능을 향상시킴 

### 단점

- 이상치가 있는 데이터에 적용할 때, 이상치들이 결과를 왜곡 시킬 수 있다. 
- 데이터를 표준화하는 과정에서 특성의 원본 분포가 변경, 특정 분석에 필요한 데이터 구조적 특성이나 본질적인 정보가 감소할 위험이 있음. 


$$ Z = \frac{X - \mu}{\sigma} $$

*   $Z$: 표준화된 새로운 데이터 값 (Z-Score)
*   $X$: 원본 데이터 값
*   $\mu$: 해당 특성(Feature) 데이터들의 평균 (Mean)

In [2]:
import pandas as pd
data = pd.DataFrame({
'몸무게(kg)': [70, 80, 60, 90, 75],
'키(cm)': [175, 180, 170, 185, 178]
})

data

   몸무게(kg)  키(cm)
0       70    175
1       80    180
2       60    170
3       90    185
4       75    178

- [StandardScaler](https://scikit-learn.org/1.6/modules/generated/sklearn.preprocessing.StandardScaler.html) : 평균이 0이고 분산이 1이 되도록 데이터를 변환하는 방법입니다. 각 특성의 값을 평균에서 빼고 표준편차로 나누어 스케일링합니다.
- [MinMaxScaler](https://scikit-learn.org/1.6/modules/generated/sklearn.preprocessing.MinMaxScaler.html) : 데이터를 0과 1 사이로 스케일링하는 방법입니다. 각 특성의 값을 최소값에서 빼고 최대값과 최소값의 차이로 나누어 스케일링합니다.
- [RobustScaler](https://scikit-learn.org/1.6/modules/generated/sklearn.preprocessing.RobustScaler.html) : 중앙값과 IQR(Interquartile Range)을 사용하여 데이터를 스케일링하는 방법입니다. 이상치에 영향을 덜 받도록 설계되었습니다.

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler
scaler.fit(data) #scaler를 data에 맞게 조정
# fit에서는 데이터에 대한 평균과 표준편차를 계산한다. 
scaled_data = scaler.transform(data) # fit 메서드에서 계산된 평균과 표준편차를 사용하여 데이터를 표준화 합니다. 
# 특성(feature)의 값에서 평균을 빼고, 그 결과를 표준편차로 나누어 준다. 
scaled_data

array([[-0.5       , -0.5195845 ],
       [ 0.5       ,  0.47961646],
       [-1.5       , -1.51878546],
       [ 1.5       ,  1.47881742],
       [ 0.        ,  0.07993608]])

In [7]:

scaled_data_df = pd.DataFrame(scaled_data, columns=['몸무게_scaled', '키_scaled'])
scaled_data_df

   몸무게_scaled  키_scaled
0        -0.5 -0.519584
1         0.5  0.479616
2        -1.5 -1.518785
3         1.5  1.478817
4         0.0  0.079936

In [8]:
import numpy as np

print(scaled_data_df['몸무게_scaled'].sum())
print(scaled_data_df['몸무게_scaled'].std())

print(scaled_data_df['키_scaled'].sum())
print(scaled_data_df['키_scaled'].std())

0.0
1.118033988749895
5.676015213396113e-15
1.1180339887498947

## 실전

```python
from sklearn.preprocessing import StandardScaler

numeric_features = ['Exercise_Duration', 'Body_Temperature(F)', 'BPM', 'Height(Feet)', 
                    'Height(Remainder_Inches)', 'Weight(lb)', 'Age']

scaler = StandardScaler()

train_data_scaled = scaler.fit_transform(train[numeric_features]) #fit transform 매서드: fit + transform
test_data_scaled = scaler.transform(test[numeric_features]) # 훈련데이터에서 계산된 평균과 표준편차를 사용하여 테스트 데이터를 표준하 하기 위함 

train_data_scaled_df = pd.DataFrame(train_data_scaled, columns=numeric_features)
test_data_scaled_df = pd.DataFrame(test_data_scaled, columns=numeric_features)

display(train_data_scaled_df.head())
display(test_data_scaled_df.head())
```